### ISSUE TITLE
Feature request: Midi input!

### ISSUE THREAD

**Issue by pgulley** [cviejo/mPD-legacy#9]
Hey! Started playing with this a few days ago- I've found myself really wishing I could interface with my midi peripherals in here- desktop PD has a midiin interface, and I know of other android apps which have simple looking midi interfaces too- this would expand the use-cases of this thing a looot

**Comment by coderofsalvation** [comment]
mobmuplat or gemmalib has this (but they require a special tool to create an interface)

**Comment by coderofsalvation** [comment]
is this issue just closed or was this actually implemented (if so, thanks! and where can I find it?)

**Comment by pgulley** [comment]
I just closed it, as it was lingering open for so long.
